[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "pyrust-projects"
dynamic = ["version", "description", "readme", "urls", "authors", "license", "keywords"]

[tool.maturin]
python-source = "python"
module-name = "rust"